# Generated by Django 3.2 on 2022-12-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursesmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
